name: security-linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  securelinux:
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
          - arm
          - riscv
          - powerpc
          - s390
          - mips
          - sparc
          - alpha
          - arc
          - csky
          - h8300
          - hexagon
          - ia64
          - loongarch
          - m68k
          - microblaze
          - nios2
          - openrisc
          - parisc
          - sh
          - sparc64
          - xtensa 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: pip
        run: |
          sudo pip3 install -U -q tuxmake==1.34.0 ${{ secrets.PRIVATE_MIRROR }}
      - name: build
        run: |
          sudo python3 -m tuxmake \
            --runtime docker \
            --quiet \
            --target-arch ${{ matrix.arch }}  \
            --directory ./linux \
            --kconfig allmodconfig \
            --toolchain gcc
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            .tuxmake/build/output/arch/${{ matrix.arch }}/boot/*Image*
            .tuxmake/build/output/vmlinux
            .tuxmake/build/output/.config